### ISSUE TITLE
Battle City does not work on Mac

### ISSUE THREAD

**Issue by Deceth** [Deceth/Battle-City#28] opened 2010-05-30 14:18 UTC
Why not? Is there an emulator that could be used? WINE? BEer... mmm

**Comment by Rushing** [comment] 2010-06-01 21:51
WINE works. Tested and confirmed. Thumbs up.

**Comment by Deceth** [comment] 2010-06-02 15:30
h2o is reporting being unable to play BC on his MAC using WINE. What versions did you test with?

**Comment by Rushing** [comment] 2010-06-02 15:31
I honestly have no clue, I litterally booted up my laptop with CentOS 5 on it, and downloaded the newest version of WINE there was. =/

**Comment by Deceth** [comment] 2010-06-02 15:44
We're talking about getting it to work on an Apple Mac, not Linux.

**Comment by Rushing** [comment] 2010-06-02 17:42
Ah sorry, my mistake, I guess I read that a little fast. Have you noticed that the wiki times are completely messed up? Apparantly, you posted your last message a day ago ;)

**Comment by Deceth** [comment] 2010-06-02 17:45
My times on the issue list are perfectly normal. Why yours are crazy is a mystery to me.

**Comment by Rushing** [comment] 2010-06-02 17:48
Screenshot link in the next post

**Comment by Rushing** [comment] 2010-06-02 17:50
http://img205.imageshack.us/img205/1492/lolwutav.jpg

=(

**Comment by rileyw** [comment] 2013-04-02 19:07
A cross-platform client may help with increasing the number of players in the game. A native client will require a transition from Win32 technologies such as DirectX to OpenGL. It is possible to use emulators or virtual machines to play games; however, players will have a poor experience if this is the only method for playing.

Other options may include adopting a different technology such as Unity3D that allow developers to publish the client to multiple platforms (http://unity3d.com/unity/multiplatform/).

**Comment by Deceth** [comment] 2013-11-07 12:36
As an interim solution, as Riley suggested, installing a virtual machine is one way you could play Battle City on any platform (so long as you can get a copy of Windows to run in the VM). This didn't used to work well, but with the increasing power of computers, these days it could be a realistic option for you if you can spare 1 or 2 GB of RAM for your VM. Most people can probably give it more than that if they close it down once they're done playing.

VirtualBox is a free virtual machine: https://www.virtualbox.org/

**Comment by rileyw** [comment] 2013-11-07 14:45
This issue can be closed since it cannot be fixed in the code.

**Closed as completed** 2013-11-12 14:04 UTC
Labels: Bug
